export const SET_RIGHT_WEIGHT_LEFT_POSITION = 'SET_RIGHT_WEIGHT_LEFT_POSITION';
export const SET_RIGHT_WEIGHT_SHAPE = 'SET_RIGHT_WEIGHT_SHAPE';
export const SET_RIGHT_WEIGHT = 'SET_RIGHT_WEIGHT';

export const SET_LEFT_WEIGHT_TOP_POSITION = 'SET_LEFT_WEIGHT_TOP_POSITION';
export const SET_LEFT_WEIGHT_LEFT_POSITION = 'SET_LEFT_WEIGHT_LEFT_POSITION';
export const SET_LEFT_WEIGHT_SHAPE = 'SET_LEFT_WEIGHT_SHAPE';
export const SET_LEFT_WEIGHT = 'SET_LEFT_WEIGHT';
export const SET_GAME_CONFIG = 'SET_GAME_CONFIG';

