export const SET_LEFT_WEIGHT_TOP_POSITION = 'SET_LEFT_WEIGHT_TOP_POSITION';
export const SET_LEFT_WEIGHT_LEFT_POSITION = 'SET_LEFT_WEIGHT_LEFT_POSITION';

export const SET_GAME_CONFIG = 'SET_GAME_CONFIG';

